#!/bin/sh

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >> "$zshrc"
    else
      printf "\\n%s\\n" "$text" >> "$zshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

update_shell() {
  local shell_path;
  shell_path="$(command -v zsh)"

  fancy_echo "Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    fancy_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_zshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
tap "caskroom/cask"

# Unix
brew "universal-ctags", args: ["HEAD"]
brew "git"
brew "openssl"
brew "rcm"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watchman"
brew "zsh"

# Programming language prerequisites and package managers
brew "libyaml" # should come after openssl
brew "coreutils"
brew "yarn"

EOF


mkdir ~/configure
git clone git@github.com:motoyasu-saburi/bokuconf.git ~/configure

#
# install custome tools
mkdir ~/tools
git clone git@github.com:maurosoria/dirsearch.git ~/tools/dirsearch
git clone git@github.com:aboul3la/Sublist3r.git ~/tools/Sublist3r
(cd ~/tools/ && wget -O dirb.tar.gz https://downloads.sourceforge.net/project/dirb/dirb/2.22/dirb222.tar.gz && tar -xf dirb.tar.gz && rm -rf dirb.tar.gz && chmod -R a+X dirb222)
git clone git@github.com:enjoiz/XXEinjector.git ~/tools/XXEinjector
git clone git@github.com:s0md3v/XSStrike.git ~/tools/XSStrike
git clone git@github.com:epinna/tplmap.git ~/tools/tplmap
git clone git@github.com:D35m0nd142/LFISuite.git ~/tools/LFISuite
git clone git@github.com:ticarpi/jwt_tool.git ~/tools/jwt_tool # Json Web Token Checker
git clone git@github.com:kost/dvcs-ripper.git ~/tools/dvcs-ripper # rip version controll system [git, svn, mercurial, etc...]
git clone git@github.com:internetwache/GitTools.git ~/tools/GitTools
pip3 install -r ~/tools/GitTools/Finder/requirements.txt
git clone git@github.com:ambionics/phpggc.git ~/tools/phpggc
# 起動がうまくいかないため一旦保留
#git clone git@github.com:lanjelot/patator.git ~/tools/patator
#(cd ~/tools/patator && python ./setup.py)
mkdir ~/tools/ysoserial
wget "https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar" -P ~/tools/ysoserial
git clone git@github.com:DataSploit/datasploit.git ~/tools/datasploit
pip install -r ~/tools/datasploit/requirements.txt --user
pip install truffleHog --user
wget https://digi.ninja/files/bucket_finder_1.1.tar.bz2 ~/tools/
tar xf ~/tools/bucket_finder_1.1.tar.bz2 -C ~/tools
# AntiVirus Alert spyware
#git clone git@github.com:leebaird/discover.git ~/tools/discover
# (cd ~/tools/discover && sudo ./update.sh)
git clone https://bitbucket.org/LaNMaSteR53/recon-ng.git ~/tools/recon-ng
pip install -r ~/tools/recon-ng/REQUIREMENTS --user
git clone git@github.com:OJ/gobuster.git ~/tools/gobuster
(cd ~/tools/gobuster/ && go get && go build && go install)
go get github.com/michenriksen/gitrob
git clone git@github.com:GerbenJavado/LinkFinder.git ~/tools/Linkfinder
(cd ~/tools/LinkFinder && sudo python setup.py install)
git clone git@github.com:jobertabma/relative-url-extractor.git ~/tools/relative-url-extractor
mv ~/configure/bokuconf/port_scanning.sh ~/tools/port_scanning.sh
git clone https://github.com/TheRook/subbrute.git ~/tools/
(git clone https://github.com/guelfoweb/knock.git ~/tools/knock && cd ~/tools/knock && sudo python setup.py install)



cat << EOS >> ~/.zshrc
alias dirsearch='~/tools/dirsearch/dirsearch.py' # directory listing
alias sublist='~/tools/Sublist3r/sublist3r.py' # directory listing
alias dirb='~/tools/dirb222/dirb'
alias xxeinjector='~/tools/XXEinjector/XXEinjector.rb' # xxe inject
alias xsstrike='~/tools/XSStrike/xsstrike.py' # xss
alias tplmap='~/tools/tplmap/tplmap.py' # Template Injection,  TODO: Set Burp Extender
alias lfisuite='~/tools/LFISuite/lfisuite.py' # local file include
alias jwt_token='~/tools/jwt_tool/jwt_tool.py' # json web token chekcer
alias dvc_ripper_git='~/tools/dvcs-ripper/rip-git.pl' # rip git
alias dvc_ripper_svn='~/tools/dvcs-ripper/rip-svn.pl' # rip svn
alias dvc_ripper_cvs='~/tools/dvcs-ripper/rip-cvs.pl' # rip cvs
alias gittools_dumper='~/tools/GitTools/Dumper/gitdumper.sh' # dump git weak web service
alias gittools_finder='~/tools/GitTools/Finder/gitfinder.py' # search git weak web searvice
alias gittools_extractor='~/tools/GitTools/Extractor/extractor.sh' # extract git weak web service
alias phpggc='~/tools/phpggc/phpggc' # php gadget chain, Requierements: PHP >5.6
alias patator='~/tools/patator/patator.py' # Brute Force [ftp, ssh, telnet, ssmtp, http, imap, ldap, etc..]
alias ysoserial='~/tools/ysoserial/ysoserial-master-SNAPSHOT.jar' # java object deserialization
alias datasploit='~/tools/datasploit/datasploit.py' # OSINT, data sploit
#alias truffleHog # search sensitive file in git
alias bucket_finder='~/tools/bucket_finder/bucket_finder.rb'
alias recon-ng='python ~/tools/recon-ng/recon-ng'
alias gobuster='go run ~/tools/gobuster/main.go'
alias gitrob='~/dev/go/bin/gitrob'
alias linkfinder='python ~/tools/LinkFinder/linkfinder.py'
alias relative-url-extractor='ruby ~/tools/relative-url-extractor/extract.rb'
alias port-scan='bash ~/tools/port_scanning.sh'
alias subbrute='~/tools/subbrute.py'
EOS

#test3
