#!/bin/sh

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >> "$zshrc"
    else
      printf "\\n%s\\n" "$text" >> "$zshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

update_shell() {
  local shell_path;
  shell_path="$(command -v zsh)"

  fancy_echo "Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    fancy_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_zshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
tap "caskroom/cask"

# Unix
brew "universal-ctags", args: ["HEAD"]
brew "git"
brew "openssl"
brew "rcm"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watchman"
brew "zsh"

# Programming language prerequisites and package managers
brew "libyaml" # should come after openssl
brew "coreutils"
brew "yarn"

EOF

fancy_echo "Configuring asdf version manager ..."
if [ ! -d "$HOME/.asdf" ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.5.0
  append_to_zshrc "source $HOME/.asdf/asdf.sh" 1
fi

install_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$url"
  fi
}

# shellcheck disable=SC1090
source "$HOME/.asdf/asdf.sh"
install_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
install_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"

install_asdf_language() {
  local language="$1"
  local version
  version="$(asdf list-all "$language" | grep -v "[a-z]" | tail -1)"

  if ! asdf list "$language" | grep -Fq "$version"; then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  fi
}

fancy_echo "Installing latest Ruby ..."
install_asdf_language "ruby"
gem update --system
gem_install_or_update "bundler"
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

fancy_echo "Installing latest Node ..."
bash "$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring"
install_asdf_language "nodejs"

if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi

#
# install custome tools
mkdir ~/tools
git clone git@github.com:maurosoria/dirsearch.git ~/tools/dirsearch
git clone git@github.com:aboul3la/Sublist3r.git ~/tools/Sublist3r
git clone git@github.com:enjoiz/XXEinjector.git ~/tools/XXEinjector
git clone git@github.com:s0md3v/XSStrike.git ~/tools/XSStrike
git clone git@github.com:epinna/tplmap.git ~/tools/tplmap
git clone git@github.com:D35m0nd142/LFISuite.git ~/tools/LFISuite
git clone git@github.com:ticarpi/jwt_tool.git ~/tools/jwt_tool # Json Web Token Checker
git clone git@github.com:kost/dvcs-ripper.git ~/tools/dvcs-ripper # rip version controll system [git, svn, mercurial, etc...]
git clone git@github.com:internetwache/GitTools.git ~/tools/GitTools
pip3 install -r ~/tools/GitTools/Finder/requirements.txt
git clone git@github.com:ambionics/phpggc.git ~/tools/phpggc
git clone git@github.com:lanjelot/patator.git ~/tools/pataor
~/tools/patator/setup.py
git clone git@github.com:frohoff/ysoserial.git ~/tools/ysoserial
mkdir ~/tools/ysoserial
wget "https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar" ~/tools/ysoserial
git clone git@github.com:DataSploit/datasploit.git ~/tools/datasploit
pip install -r ~/tools/datasploit/requirements.txt --user
pip install truffleHog --user
wget https://digi.ninja/files/bucket_finder_1.1.tar.bz2 ~/tools/
tar xf ~/tools/bucket_finder_1.1.tar.bz2 -C ~/tools
# AntiVirus Alert spyware
#git clone git@github.com:leebaird/discover.git ~/opt/discover
# (cd /opt/discover && sudo ./update.sh)

cat << EOS >> ~/.zshrc
alias dirsearch='~/tools/dirsearch/dirsearch.py' # directory listing
alias sublist='~/tools/Sublist3r/sublist3r.py' # directory listing
alias xxeinjector='~/tools/XXEinjector/XXEinjector.rb' # xxe inject
alias xsstrike='~/tools/XSStrike/xsstrike.py' # xss
alias tplmap='~/tools/tplmap/tplmap.py' # Template Injection,  TODO: Set Burp Extender
alias lfisuite='~/tools/LFISuite/lfisuite.py' # local file include
alias jwt_token='~/tools/jwt_tool/jwt_tool.py' # json web token chekcer
alias dvc_ripper_git='~/tools/dvcs-ripper/rip-git.pl' # rip git
alias dvc_ripper_svn='~/tools/dvcs-ripper/rip-svn.pl' # rip svn
alias dvc_ripper_cvs='~/tools/dvcs-ripper/rip-cvs.pl' # rip cvs
alias gittools_dumper='~/tools/GitTools/Dumper/gitdumper.sh' # dump git weak web service
alias gittools_finder='~/tools/GitTools/Finder/gitfinder.py' # search git weak web searvice
alias gittools_extractor='~/tools/GitTools/Extractor/extractor.sh' # extract git weak web service
alias phpggc='~/tools/phpggc/phpggc' # php gadget chain, Requierements: PHP >5.6
alias patator='~/tools/patator/patator.py' # Brute Force [ftp, ssh, telnet, ssmtp, http, imap, ldap, etc..]
alias ysoserial='~/tools/ysoserial/ysoserial-master-SNAPSHOT.jar' # java object deserialization
alias datasploit='~/tools/datasploit/datasploit.py' # OSINT, data sploit
#alias truffleHog # search sensitive file in git
alias bucket_finder='~/tools/bucket_finder/bucket_finder.rb'
EOS


